-
  name: 'Sending Email if httpd is not started'
  hosts: target_1
  tasks:
    -
      name: 'Checking httpd service status'
      command: 'service httpd status'
      register: result
    -
      name: 'Sending email if httpd not started'
      mail:
        to: ss0315345@gmail.com
        subject: HTTPD is Down
        body: Httpd service seems Down

      when:
        result.stdout.find('inactive') != -1
