-
  name: 'Installing NGINX'
  hosts: all
  tasks:
    -
      name: 'Installing NGINX on Debian'
      apt:
        name: nginx 
        state: present
      when:
        ansible_os_family == "debian"
    -
      name: 'Installing NGINX on Redhat'
      yum:
        name: nginx
        state: present
      when: 
        ansible_os_family == "RedHat"