-
  name: 'Installing NGINX'
  hosts: target_1
  tasks:
    -
      name: 'Installing httpd on Debian'
      apt:
        name: httpd 
        state: present
      when:
        ansible_os_family == "debian"
    -
      name: 'Installing httpd on Redhat'
      yum:
        name: httpd
        state: present
      when: 
        ansible_os_family == "RedHat"
